### ISSUE TITLE
Signature length/algorithm

### ISSUE THREAD

**Issue by ekr** [SWAN-community/owid#1]
The current document states that signature is 64 bytes but also that it is RSA. This would correspond to a 512-bit RSA signature, which is very weak.

If size is an issue, then you should use EC signatures, which are much stronger at an equivalent length (64 bytes). If there is a very strict size constraint, you could use BLS which allows for aggregating multiple signatures from different signers.

**Comment by jwrosewell** [comment]
Thank you. We will switch to EC signatures with 64 byte length prior to commercial trials to improve the solution. We'll update this issue when the documentation and code has been modified. The reference implementation will use the EC implementation from Go and within the Crypto API of web browsers.

As a reminder for those new to SWAN. The OWIDs will be transmitted and stored many trillions of times a day. As such there is a primary requirement to reduce the number of bytes used considering the risks associated with spoofing, and the other non technical methods available to uncover bad acts and actors.

**Comment by jwrosewell** [comment]
The solution and trials have been switched to ECDSA P-256. @ekr Do you consider this change addresses the issue related to the cryptographic method used to sign OWIDs?

**Comment by ekr** [comment]
Obviously I can't say for sure without looking in detail, but it should fix
the one we flagged.

**Comment by jwrosewell** [comment]
Understood. Thank you. I'll close the issue. 

Note: For those that read this n the future here are the links to the interfaces used.

[Go](https://github.com/golang/go/blob/19457a58e565ff5b480c3806fe02fbc7ccdf32f0/src/crypto/elliptic/elliptic.go#L459)
[.NET](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System.Core/System/Security/Cryptography/ECDsa.cs#L46)
[JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/verify#ecdsa)
